// ToDo define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates

// ToDo Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

    
// ToDo Test verification with incorrect proof
